### ISSUE TITLE
Search app with Elasticsearch not working. Code 500.

### ISSUE THREAD

**Issue by DoctorKnowsBetter** [hjlarry/flask-shop#105]
**Hello dear developers.**
After creating test products (`flask seed`), when trying to search using Elasticsearch, the application returns an error.
I did not change the code, I only changed the project settings in the settings.py file (for example `USE_ES = True`).

Error search app:
```
[2023-08-11 06:50:51,860] ERROR in app: Exception on /search [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/app/flaskshop/public/views.py", line 44, in search
    return render_template(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 154, in render_template
    return _render(
  File "/usr/local/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/app/flaskshop/templates/public/search_result.html", line 2, in top-level template code
    {% from 'bootstrap5/pagination.html' import render_pagination %}
  File "/app/flaskshop/templates/base.html", line 153, in top-level template code
    {% block content %}
  File "/app/flaskshop/templates/public/search_result.html", line 15, in block 'content'
    {{ render_pagination(pagination) }}
  File "/usr/local/lib/python3.10/site-packages/jinja2/runtime.py", line 777, in _invoke
    rv = self._func(*arguments)
  File "/usr/local/lib/python3.10/site-packages/flask_bootstrap/templates/base/pagination.html", line 53, in template
    {%- for page in pagination.iter_pages() %}
  File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 439, in iter_pages
    for num in xrange(1, self.pages + 1):
  File "/usr/local/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py", line 374, in pages
    pages = int(ceil(self.total / float(self.per_page)))
TypeError: unsupported operand type(s) for /: 'AttrDict' and 'float'
```
![screenshot-2023 08 11-10:00:54](https://github.com/hjlarry/flask-shop/assets/111871367/e18b70bd-4f07-44c1-88c9-bef4cc050663)
![screenshot-2023 08 11-10:02:44](https://github.com/hjlarry/flask-shop/assets/111871367/684e5f91-85d0-497b-af7e-e014d167429d)

**Comment by hjlarry** [comment]
fixed( test with docker env )
